### ISSUE TITLE
Typo in vertalingen latyer i.p.v. later

### ISSUE THREAD

**Issue by peeveeone** [AppiePau/devshed-tools#6]
<data name="DateMustBeLaterThan" xml:space="preserve">
    <value>De datum moet latyer zijn dan '{0}'.</value>
  </data>

Met vriendelijke groet namens Dick Verhoeven. ;)

**Comment by AppiePau** [comment]
Hi,

Dank je! Bij deze aangepast in commit cdb80d0ec1295c0957d71c0fb04db1b0f1d0c0a5.

Eveneens de groeten aan Dick!
